### ISSUE TITLE
Can't access non-fish man pages

### ISSUE THREAD

**Issue by PatrickF1** [patrickf3139/colored_man_pages.fish#4]
With this plugin installed. I can no longer run commands like `man grep`. But if I uninstall I can access it just fine. @kidonng can you repro as well?

**Comment by kidonng** [comment]
Yeah, I can reproduce. It seems `man` expects something like `MANPATH=/usr/local/Cellar/fish/3.2.2_1/share/fish/man:` (notice the extra `:`) to fallback to other man pages. That equals to an extra empty string in fish.

**Comment by PatrickF1** [comment]
Thank you for the great investigation!
