### ISSUE TITLE
fatal: couldn't find remote ref refs/heads/master

### ISSUE THREAD

**Issue by ar1ja** [patrickf3139/colored_man_pages.fish#6]
omf doesn't update:
```
╭─ ari at ari-arch in ~
╰> omf update 
Oh My Fish is up to date.
You are now using Oh My Fish version 7.
Updating https://github.com/oh-my-fish/packages-main master... Done!
archlinux is already up-to-date.
fatal: couldn't find remote ref refs/heads/master
Could not update colored_man_pages.fish.
default is already up-to-date.
````

tried both
```shell
$ omf install https://github.com/patrickf1/colored_man_pages.fish
$ omf install colored-man-pages
```

**Comment by ar1ja** [comment]
at least for now i just git cloned it and put functions/* in my fish functions

**Comment by PatrickF1** [comment]
TBH, I don't use OMF anymore so I'm not sure why. It's possible it's b/c https://github.com/oh-my-fish/packages-main/blob/master/packages/colored-man-pages is pointing to this repo before it was renamed AND I changed my username.  I'd try to update it but as you can see, the OMF team has merged a single PR to the packages repo since this time last year.

Can you try asking OMF for help?

**Comment by PatrickF1** [comment]
I should probably just remove OMF from support since I haven't kept up-to-date with them and don't know how it works anymore, sorry :(

**Comment by ar1ja** [comment]
> TBH, I don't use OMF anymore so I'm not sure why. It's possible it's b/c https://github.com/oh-my-fish/packages-main/blob/master/packages/colored-man-pages is pointing to this repo before it was renamed AND I changed my username. I'd try to update it but as you can see, the OMF team has merged a single PR to the packages repo since this time last year.
> 
> Can you try asking OMF for help?

i can try

**Comment by ar1ja** [comment]
> I should probably just remove OMF from support since I haven't kept up-to-date with them and don't know how it works anymore, sorry :(

oh alright:), i'll just keep it as simple git-clone

**Comment by PatrickF1** [comment]
Thank you! I'm sincerely sorry I couldn't be of more help. Please let me know how you resolve this when you do.

**Comment by ar1ja** [comment]
i made a PR in the package repo
https://github.com/oh-my-fish/packages-main/pull/144/
they might except it, might not, i don't know any other way to resolve it besides git cloning it,
thanks for the help:)

**Comment by PatrickF1** [comment]
Thank you!
